version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    tty: true
    depends_on:
      - db
    