version: "3"

services:
  db:
    container_name: django-db_v4.0.3
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    container_name: django-app_v4.0.3
    build: .
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    tty: true
    depends_on:
      - db
    